import { Platform } from 'react-native'

const HORIZONTAL_SPACING_BASE = Platform.OS === 'web' ? 4 : 2
const VERTICAL_SPACING_BASE = 4

const icons = {
  home: require('../../assets/icons/home-icon.png'),
  home_android: require('../../assets/icons/home-icon-24.png'),
  rightArrow: require('../../assets/icons/right-arrow.png'),
  tick: require('../../assets/icons/tick.png'),
  plus: require('../../assets/icons/plus.png'),
  back: require('../../assets/icons/back.png'),
  menu: require('../../assets/icons/menu.png'),
  call: require('../../assets/icons/call.png'),
  pin: require('../../assets/icons/pin.png'),
  userFilled: require('../../assets/icons/user-filled.png'),
  mapLocation: require('../../assets/map-location.png'),
  driver: require('../../assets/driver.png'),
  markerImage: require('../../assets/icons/marker.png'),
  menuHamburger: require('../CoreAssets/hamburger-menu-icon.png'),
  logo: require('../../assets/applogo.png'),
  backArrow: require('../../assets/icons/backArrow.png'),
  userAvatar: require('../../assets/icons/default-avatar.jpg'),
  close: require('../CoreAssets/close-x-icon.png'),
  userAvatar: require('../../assets/icons/default-avatar.jpg'),
  backArrow: require('../../assets/icons/arrow-back-icon.png'),
  menuHamburger: require('../../assets/icons/menu-hamburger.png'),
  homeUnfilled: require('../../assets/icons/home-unfilled.png'),
  homefilled: require('../../assets/icons/home-filled.png'),
  home_android: require('../../assets/icons/home-icon-24.png'),
  search: require('../../assets/icons/search.png'),
  magnifier: require('../../assets/icons/magnifier.png'),
  commentUnfilled: require('../../assets/icons/comment-unfilled.png'),
  commentFilled: require('../../assets/icons/comment-filled.png'),
  friendsUnfilled: require('../../assets/icons/friends-unfilled.png'),
  friendsFilled: require('../../assets/icons/friends-filled.png'),
  profileUnfilled: require('../../assets/icons/profile-unfilled.png'),
  profileFilled: require('../../assets/icons/profile-filled.png'),
  camera: require('../../assets/icons/camera.png'),
  cameraFilled: require('../../assets/icons/camera-filled.png'),
  inscription: require('../../assets/icons/inscription.png'),
  more: require('../../assets/icons/more.png'),
  send: require('../../assets/icons/send.png'),
  pinpoint: require('../../assets/icons/pinpoint.png'),
  checked: require('../../assets/icons/checked.png'),
  bell: require('../../assets/icons/bell.png'),
  surprised: require('../../assets/icons/wow.png'),
  laugh: require('../../assets/icons/crylaugh.png'),
  cry: require('../../assets/icons/crying.png'),
  thumbsupUnfilled: require('../../assets/icons/thumbsup-unfilled.png'),
  heartUnfilled: require('../../assets/icons/heart-unfilled.png'),
  like: require('../../assets/icons/blue-like.png'),
  love: require('../../assets/icons/red-heart.png'),
  angry: require('../../assets/icons/anger.png'),
  cameraRotate: require('../../assets/icons/camera-rotate.png'),
  videoCamera: require('../../assets/icons/video-camera.png'),
  libraryLandscape: require('../../assets/icons/library-landscape.png'),
  playButton: require('../../assets/icons/play-button.png'),
  logout: require('../../assets/icons/logout-drawer.png'),
  sound: require('../../assets/icons/sound.png'),
  soundMute: require('../../assets/icons/sound_mute.png'),
  users_android: require('../../assets/icons/users-icon-48.png'),
  user_android: require('../../assets/icons/account-detail.png'),
}

const lightColors = {
  primaryBackground: '#ffffff',
  secondaryBackground: '#ffffff',
  primaryForeground: '#434343',
  secondaryForeground: '#595959',
  foregroundContrast: 'white',
  primaryText: '#434343',
  secondaryText: '#7e7e7e',
  hairline: '#e0e0e0',
  grey0: '#fafafa',
  grey1: '#cecdce',
  grey2: '#efefef',
  grey3: '#f5f5f5',
  grey4: '#c4c4c4',
  grey5: '#b3b3b3',
  grey6: '#d6d6d6',
  grey9: '#939393',
  red: '#ea0606',
}

const InstamobileTheme = {
  colors: {
    light: lightColors,
    'no-preference': lightColors,
    dark: {
      primaryBackground: '#121212',
      secondaryBackground: '#000000',
      primaryForeground: '#434343',
      secondaryForeground: '#8442bd',
      foregroundContrast: 'white',
      primaryText: '#ffffff',
      secondaryText: '#c5c5c5',
      hairline: '#222222',
      grey0: '#0a0a0a',
      grey1: '#b3b3b3',
      grey2: '#c4c4c4',
      grey3: '#f5f5f5',
      grey4: '#efefef',
      grey5: '#cecdce',
      grey6: '#f5f5f5',
      grey9: '#eaeaea',
      red: '#ea0606',
    },
  },
  spaces: {
    horizontal: {
      s: 2 * HORIZONTAL_SPACING_BASE,
      m: 4 * HORIZONTAL_SPACING_BASE,
      l: 6 * HORIZONTAL_SPACING_BASE,
      xl: 8 * HORIZONTAL_SPACING_BASE,
    },
    vertical: {
      s: 2 * VERTICAL_SPACING_BASE,
      m: 4 * VERTICAL_SPACING_BASE,
      l: 6 * VERTICAL_SPACING_BASE,
      xl: 8 * VERTICAL_SPACING_BASE,
    },
  },
  fontSizes: {
    xxs: 8,
    xs: 12,
    s: 14,
    m: 16,
    l: 18,
    xl: 24,
    xxl: 32,
  },
  fontWeights: {
    s: '400',
    m: '600',
    l: '800',
  },
  icons: icons,
  // color, font size, space / margin / padding, vstack / hstack
  button: {
    borderRadius: 8,
  },
}

export default InstamobileTheme
